//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by VegaConnect.rc
//
#define IDAPPLY                         3
#define IDCONNECT                       3
#define IDSETASDEFAULT                  4
#define IDM_ABOUTBOX                    0x0010
#define IDD_ABOUTBOX                    100
#define IDS_ABOUTBOX                    101
#define IDD_VEGACONNECT_DIALOG          102
#define IDS_GRID_SEL                    102
#define IDS_GRID_NAME                   103
#define IDS_GROUP                       104
#define IDS_GRID_LASTDATE               105
#define IDS_GRID_DATACOUNT              106
#define IDS_ADDRESS                     107
#define IDS_ACTION                      108
#define IDS_GRID_N                      109
#define IDS_GRID_DATA                   110
#define IDS_TIME                        111
#define IDS_ALL                         112
#define IDS_MENU                        113
#define IDS_LOADALLDATA                 114
#define IDS_CLEARLIMITS                 115
#define IDS_CLEARERROR                  116
#define IDS_CONNECTIONLOST              117
#define IDS_QUERY                       118
#define IDS_PROCESSING                  119
#define IDS_NOCONNECTION                120
#define IDS_MAINHEADER                  121
#define IDS_QUERYERROR                  122
#define IDS_DATAUPDATE                  123
#define IDS_UPDATING                    124
#define IDS_ALARM                       125
#define IDS_TEMPERATURE                 126
#define IDS_DELDEVICE_Q                 127
#define IDS_ADDDEVCIE                   128
#define IDS_MODDEVICE                   129
#define IDD_ADDDEVICEDLG                130
#define IDS_DELDEVICE                   130
#define IDD_GRAPHNETSETTINGS            131
#define IDS_NEEDADDRES                  131
#define IDD_SETTINGSDLG                 132
#define IDS_NEEDNAME                    132
#define IDD_AXISSETTINGS                133
#define IDS_GROUPNOTSET_Q               133
#define IDD_GRIDSETTINGS                134
#define IDS_NEEDUSERNAME                134
#define IDD_SPECIALGSETTINGS            135
#define IDS_NEEDPASSWORD                135
#define IDS_PASSWNOTMATCH               136
#define IDD_CURVESETTINGS               137
#define IDS_INCORRECTRESPONSE           137
#define IDD_CURVETYPE                   138
#define IDS_USERADDERROR                138
#define IDR_GRAPHMENU                   139
#define IDD_USERDLG                     139
#define IDS_CHANGEUSERPASSWORD          139
#define IDS_ERROR                       140
#define IDS_DEVICEADDERROR              141
#define IDS_SUCCESSFULLCONNECT          142
#define IDS_DELETEUSER_Q                143
#define IDS_LG_MAIN                     144
#define IDD_DIALOG1                     145
#define IDS_NFC_OPENERROR               145
#define IDD_FILTER                      146
#define IDS_REPLACEBATTERY_Q            146
#define IDS_LG_SENSORS                  147
#define IDS_LG_ALARMS                   148
#define IDD_PROGRESS                    149
#define IDS_SETTINGSLOADNEEDED          149
#define IDD_LG_MAIN                     150
#define IDS_LG_SETTINGS                 150
#define IDS_LG_RADIO                    151
#define IDD_GETNAME                     152
#define IDS_WRONG_KEYLENGTH             152
#define IDS_LG_WORKSTAT                 153
#define IDS_PARAMETER                   154
#define IDS_VALUE                       155
#define IDS_LG_GRAPH                    156
#define IDS_GAS                         157
#define IDS_NEEDONEGAS                  158
#define IDS_EXECUTING                   159
#define IDS_DONE                        160
#define IDS_NEEDSETCONCENTRATION        161
#define IDS_CANCELFORALL_Q              162
#define IDD_GROUPINFO                   162
#define IDS_DEVICEINSTALLED             163
#define IDS_READERINSTALLED             164
#define IDD_RCTRANSLATE                 164
#define IDS_UNKNOWNREADER               165
#define IDS_LG_LOG                      166
#define IDD_RICHEDIT                    166
#define IDS_CLEARLOG_Q                  167
#define IDS_STOPOPERATION               168
#define IDS_LG_FIRMWARE                 169
#define IDS_CALIBRATION                 170
#define IDS_DEVICECALIBRATIONCOMPLETE   171
#define IDS_DEVICECALIBRATIONFAILED     172
#define IDS_DEVICECALIBRATIONTERMINATED 173
#define IDS_CALIBRATIONCOMPLETE         174
#define IDS_DEVICE                      175
#define IDS_CRCERROR                    176
#define IDS_GETLOGBLOCK                 177
#define IDS_LOGCOMPLETE                 178
#define IDS_LOGFAILED                   179
#define IDS_SWITCHINGBOOTLOADER         180
#define IDD_SELECTPOINTTYPE             181
#define IDS_INBOOTLOADER                181
#define IDS_FLASHERASE                  182
#define IDS_FLASHERASED                 183
#define IDS_WRITEFLASHBLOCK             184
#define IDS_SENDLASTBYTES               185
#define IDS_FIRMWARECOMPLETE            186
#define IDS_FIRMWAREERROR               187
#define IDS_WAIT                        188
#define IDS_MEASURE                     189
#define IDS_MEASURED                    190
#define IDS_COEFFCORRECTED              191
#define IDS_COEFFCALCULATED             192
#define IDS_STARTCHECKING               193
#define IDS_REMOVEZEROSENSOR            194
#define IDS_MEASUREDCALIBRATED          195
#define IDS_COEFFTRANSFERERROR          196
#define IDS_DIFFERENCE                  197
#define IDS_INCORRECTDATA               198
#define IDS_STARTFACTORYRESET           199
#define IDS_FACTORYRESETCOMPLETE        200
#define IDS_LOGTERMINATED               201
#define IDS_PUSHBUTTONTOSTART           202
#define IDS_DEVICECALIBRATIONPOSSIBLEFAILURE 203
#define IDS_APPNOTRESPONDING            204
#define IDS_CYCLICALLY                  205
#define IDS_STOP                        206
#define IDS_MONITORING                  207
#define IDS_FACTORYRESETCOMPLETEERROR   208
#define IDS_BREAKALLANDCLOSE_Q          209
#define IDS_BREAKMONITORING_Q           210
#define IDS_SETUNITSCOMPLETE            211
#define IDS_SETUNITSERROR               212
#define IDS_STARTLIMITTEST              213
#define IDS_LIMITTESTDONE               214
#define IDS_LIMITTESTERROR              215
#define IDS_COEFF                       216
#define IDS_COEFFS                      216
#define IDS_SENSORSTATUS                217
#define IDS_SENSORACC                   218
#define IDS_MEASUREDIAP                 219
#define IDS_VOLTDIAP                    220
#define IDS_ENABLESETALL_Q              221
#define IDS_LG_MULTIPLE                 222
#define IDS_LOGTIMEOUT                  223
#define IDS_DEVICEMODE                  224
#define IDS_DISABLEALARM                225
#define IDS_NEEDONEPARAMETER            226
#define IDS_UNITS                       227
#define IDS_ATTENTION                   228
#define IDS_CHECKGASFLOW                229
#define IDS_COEFFICIENT                 230
#define IDS_ERRORCAUSE                  231
#define IDS_INFORMATION                 232
#define IDS_LOGCOMPLETEWITHERROR        233
#define IDD_SETHOTKEYDLG                233
#define IDS_PRECISIONS                  234
#define IDS_NOANSWER                    235
#define IDS_MIPEXDONE                   236
#define IDS_MIPEXDONEWITHERROR          237
#define IDS_LG_SAVE                     238
#define IDS_SETTINGS                    239
#define IDS_ALLSETTINGS                 240
#define IDS_ALLCOEFF                    241
#define IDS_BASESETTINGS                242
#define IDS_SETSAVENAME                 243
#define IDS_REPLACESETTINGS_Q           244
#define IDS_RESTORE                     245
#define IDS_RESTORING                   246
#define IDS_SAVEINGSETTINGS             247
#define IDS_SETTINGSNOTLOADED           248
#define IDS_SERIALNO                    249
#define IDS_AUTOZERO                    250
#define IDS_CRCERRORCOMMAND             251
#define IDS_STOPALL                     252
#define IDS_CANNOTADDHOTKEY             253
#define IDS_ADDHOTKEY                   254
#define IDS_MODHOTKEY                   255
#define IDS_DELHOTKEY                   256
#define IDS_YES_                        257
#define IDS_NO_                         258
#define IDS_CANCEL_                     259
#define IDS_SETTINGSNOTFORTHISDEVICE    260
#define IDS_LIMIT                       261
#define IDS_TEST                        262
#define IDS_LOGPERIOD                   263
#define IDS_VIBROPOWER                  264
#define IDS_USERSETTINGS                265
#define IDS_SERVICESETTINGS             266
#define IDS_LOGPERIODWORK               267
#define IDS_LOGPERIODALARM              268
#define IDS_RESTORETYPE                 269
#define IDS_CANTRESTORESETTINGS         270
#define IDS_RESTOREALERT                271
#define IDS_ALLUSERSETTINGS             272
#define IDS_RADIOCHANSETTINGS           273
#define IDS_DIESEL                      274
#define IDS_KEROSENE                    275
#define IDS_AV_GASOLINE                 276
#define IDS_UNLEADED_GASOLINE           277
#define IDS_GASOLINE_VAPOUR             278
#define IDS_HYDROCARBON_MIX             279
#define IDS_DIESEL_SHORT                280
#define IDS_KEROSENE_SHORT              281
#define IDS_AV_GASOLINE_SHORT           282
#define IDS_UNLEADED_GASOLINE_SHORT     283
#define IDS_GASOLINE_VAPOUR_SHORT       284
#define IDI_MAIN                        284
#define IDS_HYDROCARBON_MIX_SHORT       285
#define IDS_CH4                         286
#define IDS_C3H8                        287
#define IDD_GRIDINFO                    287
#define IDS_CO2                         288
#define IDS_C2H6                        289
#define IDD_DELAYEDCOMMANDEDITOR        289
#define IDS_C4H10                       290
#define IDS_C5H12                       291
#define IDD_GRAPH                       291
#define IDS_C3H6                        292
#define IDS_CH3OH                       293
#define IDD_CAMERASETTINGS              293
#define IDS_C6H6                        294
#define IDS_C7H16                       295
#define IDS_O2                          296
#define IDS_CO                          297
#define IDS_H2S                         298
#define IDS_CL2                         299
#define IDS_NH3                         300
#define IDS_SO2                         301
#define IDS_NO2                         302
#define IDS_H2                          303
#define IDS_MPC                         304
#define IDS_LIMITSMUSTBEINRANGE         305
#define IDS_CH3SH                       306
#define IDS_POSMUSTBEDIFF               307
#define IDS_SELECTSAVEPATH              308
#define IDS_ACETONE                     309
#define IDS_RSSI_LEVEL0                 310
#define IDS_RSSI_LEVEL1                 311
#define IDS_RSSI_LEVEL2                 312
#define IDS_RSSI_LEVEL3                 313
#define IDS_RSSI_LEVEL4                 314
#define IDS_RSSI_LEVEL5                 315
#define IDS_RSSI_CURRENT                316
#define IDS_RSSI_NEIGHBOR               317
#define IDS_LEVEL                       318
#define IDS_MLN_UNITS                   319
#define IDS_MGM3_UNITS                  320
#define IDS_VOLTOLEL                    321
#define IDS_PPMTOMG                     322
#define IDS_WRONGBOOTLOADER             323
#define IDS_VOL_UNITS                   324
#define IDS_LEL_UNITS                   325
#define IDS_MIPEXDONE2                  326
#define IDS_MIPEXDONEWITHERROR2         327
#define IDS_NOMIPEXBACKUP               328
#define IDS_COPPMTOMG                   329
#define IDS_H2SPPMTOMG                  330
#define IDS_O2PPMTOMG                   331
#define IDS_C2H5SH                      332
#define IDS_LG_DELAYEDCOMMAND           333
#define IDS_COMMAND                     334
#define IDS_FROMSTART                   335
#define IDS_FROMPREVCOMMAND             336
#define IDS_DELETE                      337
#define IDS_STARTALL                    338
#define IDS_STATUS                      339
#define IDB_CLOSE                       340
#define IDS_PROFILENAME                 340
#define IDS_NAMEALREADYEXISTS           341
#define IDS_NEW                         342
#define IDS_UP                          343
#define IDS_DOWN                        344
#define IDS_DUBLICATE                   345
#define IDS_REMOVEALL                   346
#define IDS_DCADONE                     347
#define IDS_DCADONEWITHERROR            348
#define IDS_C2H4O                       349
#define IDS_GASPOS                      350
#define IDS_FREEZEMASK0                 351
#define IDS_FREEZEMASK1                 352
#define IDS_FREEZEMASK2                 353
#define IDS_FREEZEMASK4                 354
#define IDS_FREEZEMASK5                 355
#define IDS_FREEZEMASK6                 356
#define IDS_FREEZEMASK7                 357
#define IDS_FREEZEMASK8                 358
#define IDS_FREEZEMASK9                 359
#define IDS_FREEZEMASK15                360
#define IDS_GAS_NO                      361
#define IDS_STOPPED                     362
#define IDS_CAMERAERROR                 363
#define IDS_CONNECTIONERROR             364
#define IDS_TWAIT                       365
#define IDS_GASPUFFING                  366
#define IDS_TOVER                       367
#define IDS_OFF                         368
#define IDD_LONGGASDLG                  900
#define IDD_LG_SENSORS                  901
#define IDD_LG_ALARMS                   902
#define IDD_LG_SETTINGS                 903
#define IDD_LG_RADIO                    904
#define IDD_LG_WORKSTAT                 905
#define IDD_LG_MIPEX                    906
#define IDD_LG_GRAPH                    907
#define IDD_LG__LOG                     908
#define IDD_LG_FIRMWARE                 909
#define IDD_LG_MULTIPLE                 910
#define IDD_LG_SAVE                     911
#define IDD_LG_WIFI                     912
#define IDD_LG_DELAYED                  913
#define IDC_GRID                        1000
#define IDC_TEST                        1001
#define IDC_CHECK                       1001
#define IDC_DEVICES                     1002
#define IDC_STATIC_GRAPH                1003
#define IDC_COMBO_GRAPH                 1004
#define IDC_XAXISWIDTH                  1004
#define IDC_ADDRESS                     1005
#define IDC_XAXISTYPE                   1005
#define IDC_PORT                        1006
#define IDC_CHECK_SHOWAXIS              1006
#define IDC_EUI                         1006
#define IDC_CHECK_TICKS                 1007
#define IDC_STATIC_GRAPH_SIGNAL         1007
#define IDC_NAME                        1007
#define IDC_PASSWORD                    1007
#define IDC_VERTWIDTH                   1008
#define IDC_TICKWIDTH                   1008
#define IDC_COMBO_GRAPH2                1008
#define IDC_NAME2                       1008
#define IDC_PWD                         1008
#define IDC_VERTTYPE                    1009
#define IDC_CHECK_SCALERS               1009
#define IDC_DEVICES2                    1009
#define IDC_GROUP                       1009
#define IDC_PWD2                        1009
#define IDC_CHECK_SHOWVERT              1010
#define IDC_TAB                         1010
#define IDC_ADDDEVICE                   1010
#define IDC_CHECK_SHOWHORZ              1011
#define IDC_HORZWIDTH                   1013
#define IDC_GRID_DEVICES                1013
#define IDC_HORZTYPE                    1014
#define IDC_SETTINGS                    1014
#define IDFONT                          1015
#define IDC_EXPORT                      1015
#define IDC_CHECK_ARROWS                1016
#define IDC_STATIC_INFO                 1016
#define IDTITLEFONT                     1017
#define IDC_COMBO_USER                  1017
#define IDC_EDIT_TICKSTEP               1018
#define IDC_COMBO_LANG                  1018
#define IDC_EDIT_TICKNUM                1019
#define IDC_LINKDEVICES                 1019
#define IDC_CHECK_AUTOTICK              1020
#define IDC_ADDUSER                     1020
#define IDC_CHECK_TOPBORDER             1021
#define IDC_MODUSER                     1021
#define IDC_STATIC_GROUP                1021
#define IDC_CHECK_RIGHTBORDER           1022
#define IDC_CHOOSECOLOR                 1022
#define IDC_DELUSER                     1022
#define IDC_STATIC_GRAPHDATA            1022
#define IDC_CHOOSECOLORY                1023
#define IDC_STATIC_DATA                 1023
#define IDC_CHOOSECOLORX                1024
#define IDC_STATIC_SIGNAL               1024
#define IDC_FONTCOLOR                   1025
#define IDC_UPDATEPERIOD                1026
#define IDC_FONTBACKCOLOR               1027
#define IDC_SELECTPERIOD                1027
#define IDC_CHECK1                      1027
#define IDC_CHECK_T                     1027
#define IDC_CHECK_BEEP                  1027
#define IDC_CHECK_O2STATUS              1027
#define IDC_CHECK_EN1                   1027
#define IDC_CHECK_LOGPERIOD             1027
#define IDC_MIPEX4                      1027
#define IDC_CHECK_AUTOCONNECT           1027
#define IDC_SHOWBADDATA                 1027
#define IDC_CHECK_FROMCTIME             1028
#define IDC_CO_STATUS                   1028
#define IDC_CHECK_EN2                   1028
#define IDC_CHECK_BEEP2                 1028
#define IDC_CHECK_SKIPSELFTEST          1028
#define IDC_CHECK_DHCP                  1028
#define IDC_STATIC_DEVTABLE             1029
#define IDC_CHECK_H2SSTATUS             1029
#define IDC_CHECK_EN3                   1029
#define IDC_CHECK_TCPSERVER             1029
#define IDC_CHECK_SKIPSELFTESTTRANSPORT 1029
#define IDC_GAS1                        1030
#define IDC_CHECK_CH4STATUS             1030
#define IDC_GAS2                        1031
#define IDC_UPDATEONSTART               1031
#define IDC_CHECK_O2_ZERO               1031
#define IDC_CHECK_C3H8_STATUS           1031
#define IDC_GAS3                        1032
#define IDC_CO_ZERO                     1032
#define IDC_CHECK_CO_ZERO               1032
#define IDC_FCOMMAND                    1032
#define IDC_GAS4                        1033
#define IDC_CHECK_H2S_ZERO              1033
#define IDC_ALL                         1034
#define IDC_CHECK_CH4_ZERO              1034
#define IDC_STATIC_GROUPGRAPH           1035
#define IDC_WIDTH                       1036
#define IDC_RADIO_RSSI                  1036
#define IDC_TYPE                        1037
#define IDC_RADIO_RSSI2                 1037
#define IDC_CHECK_O2_CALIB              1037
#define IDC_STATIC_GRAPHGROUP           1038
#define IDC_CO_CALIB                    1038
#define IDC_CHECK_CO_CALIB              1038
#define IDC_STATIC_DEVICES              1039
#define IDC_STATIC_GRIDDEVICES          1039
#define IDC_CHECK_H2S_CALIB             1039
#define IDC_CURVECOLOR                  1040
#define IDC_STATIC_GRIDDATA             1040
#define IDC_CHECK_CH4_CALIB             1040
#define IDC_CURVECOLOR2                 1041
#define IDC_TAB1                        1041
#define IDC_CURVECOLOR3                 1042
#define IDC_STATIC_CHILD                1042
#define IDC_CURVECOLOR4                 1043
#define IDC_EDIT_SWVER                  1043
#define IDC_CURVECOLOR5                 1044
#define IDC_EDIT_IDSENSOR               1044
#define IDC_EDIT_IDCPU                  1045
#define IDC_REFRESHDEVINFO              1046
#define IDC_BLINK                       1047
#define IDC_BEEP                        1048
#define IDC_REBOOT                      1049
#define IDC_REPLACEBATTERY              1050
#define IDC_SERIALNO                    1051
#define IDC_SETSERIALNO                 1052
#define IDC_LOGTIMEOUT                  1053
#define IDC_SETLOGTIMEOUT               1054
#define IDC_SPIN1                       1055
#define IDC_COMBO_TYPE                  1056
#define IDC_CHECK_VIBRO                 1056
#define IDC_SPIN2                       1056
#define IDC_FILTERSTEP                  1057
#define IDC_CHECK_ALARM                 1057
#define IDC_SPIN3                       1057
#define IDC_FILTERWINDOW                1058
#define IDC_SETDEVICEMODE               1058
#define IDC_SPIN4                       1058
#define IDC_DEVICEMODE                  1059
#define IDC_SPIN5                       1059
#define IDC_NFCPOWERDOWNENABLE          1060
#define IDC_SPIN6                       1060
#define IDC_PROGRESS                    1061
#define IDC_NFCPOWERDOWNDISABLE         1061
#define IDC_RX1SPIN                     1061
#define IDC_TIME                        1062
#define IDC_RX2SPIN                     1062
#define IDC_DATE                        1063
#define IDC_BW                          1063
#define IDC_EDITNAME                    1064
#define IDC_CHECK_DAYLIGHT              1064
#define IDC_CR                          1064
#define IDC_DIGITS                      1065
#define IDC_SETDATETIME                 1065
#define IDC_STATIC_1                    1065
#define IDC_WINDOW                      1065
#define IDC_SETDATETIMECOMP             1066
#define IDC_EDIT1                       1066
#define IDC_JOINDELAYSPIN1              1066
#define IDC_SPIN                        1067
#define IDC_STATIC_2                    1067
#define IDC_EDIT_CO                     1067
#define IDC_ANSWER                      1067
#define IDC_JOINDELAYSPIN2              1067
#define IDC_LOGTIMEOUT2                 1067
#define IDC_EDIT2                       1068
#define IDC_JOINNUMSPIN                 1068
#define IDC_SETLOGTIMEOUT2              1068
#define IDC_STATIC_3                    1069
#define IDC_EDIT_CH4                    1069
#define IDC_SPIN_RX                     1069
#define IDC_SPIN7                       1069
#define IDC_EDIT3                       1070
#define IDC_WEEKTOSCALE                 1070
#define IDC_STATIC_4                    1071
#define IDC_SETWEEKTOSCALE              1071
#define IDC_EDIT4                       1072
#define IDC_SPIN_WEEKTOSCALE            1072
#define IDC_STATIC_5                    1073
#define IDC_EDIT5                       1074
#define IDC_STATIC_6                    1075
#define IDC_EDIT6                       1076
#define IDC_STATIC_7                    1077
#define IDC_EDIT7                       1078
#define IDC_STATIC_8                    1079
#define IDC_EDIT8                       1080
#define IDC_STATIC_9                    1081
#define IDC_EDIT9                       1082
#define IDC_STATIC_10                   1083
#define IDC_EDIT10                      1084
#define IDC_STATIC_11                   1085
#define IDC_EDIT11                      1086
#define IDC_STATIC_12                   1087
#define IDC_EDIT12                      1088
#define IDC_STATIC_13                   1089
#define IDC_EDIT13                      1090
#define IDC_STATIC_14                   1091
#define IDC_EDIT14                      1092
#define IDC_STATIC_15                   1093
#define IDC_EDIT15                      1094
#define IDC_STATIC_16                   1095
#define IDC_EDIT16                      1096
#define IDC_STATIC_17                   1097
#define IDC_EDIT17                      1098
#define IDC_STATIC_18                   1099
#define IDC_EDIT18                      1100
#define IDC_STATIC_19                   1101
#define IDC_EDIT19                      1102
#define IDC_STATIC_20                   1103
#define IDC_EDIT20                      1104
#define IDC_STATIC_21                   1105
#define IDC_EDIT21                      1106
#define IDC_STATIC_22                   1107
#define IDC_EDIT22                      1108
#define IDC_STATIC_23                   1109
#define IDC_EDIT23                      1110
#define IDC_STATIC_24                   1111
#define IDC_EDIT24                      1112
#define IDC_STATIC_25                   1113
#define IDC_EDIT25                      1114
#define IDC_STATIC_26                   1115
#define IDC_EDIT26                      1116
#define IDC_STATIC_27                   1117
#define IDC_EDIT27                      1118
#define IDC_STATIC_28                   1119
#define IDC_EDIT28                      1120
#define IDC_STATIC_29                   1121
#define IDC_EDIT29                      1122
#define IDC_STATIC_30                   1123
#define IDC_EDIT30                      1124
#define IDC_STATIC_31                   1125
#define IDC_EDIT31                      1126
#define IDC_STATIC_32                   1127
#define IDC_EDIT32                      1128
#define IDC_STATIC_33                   1129
#define IDC_EDIT33                      1130
#define IDC_STATIC_34                   1131
#define IDC_EDIT34                      1132
#define IDC_STATIC_35                   1133
#define IDC_EDIT35                      1134
#define IDC_STATIC_36                   1135
#define IDC_EDIT36                      1136
#define IDC_STATIC_37                   1137
#define IDC_EDIT37                      1138
#define IDC_STATIC_38                   1139
#define IDC_EDIT38                      1140
#define IDC_STATIC_39                   1141
#define IDC_EDIT39                      1142
#define IDC_LIST2                       1143
#define IDC_STATIC_40                   1143
#define IDC_EDIT40                      1144
#define IDC_STATIC_41                   1145
#define IDC_EDIT41                      1146
#define IDC_STATIC_42                   1147
#define IDC_EDIT42                      1148
#define IDC_STATIC_43                   1149
#define IDC_EDIT43                      1150
#define IDC_STATIC_44                   1151
#define IDC_EDIT44                      1152
#define IDC_STATIC_45                   1153
#define IDC_EDIT45                      1154
#define IDC_STATIC_46                   1155
#define IDC_EDIT46                      1156
#define IDC_STATIC_47                   1157
#define IDC_EDIT47                      1158
#define IDC_STATIC_WINDOW               1159
#define IDC_SET_O2COEFF                 1159
#define IDC_SET_O2COEFFDEF              1160
#define IDC_STATIC_RX1DELAY             1160
#define IDC_SET_COCOEFF                 1161
#define IDC_STATIC_RX2DELAY             1161
#define IDC_SET_COCOEFFDEF              1162
#define IDC_STATIC_DEVEUI               1162
#define IDC_SET_H2SCOEFF                1163
#define IDC_STATIC_JOINEUI              1163
#define IDC_SET_H2SCOEFFDEF             1164
#define IDC_STATIC_ROOTKEY              1164
#define IDC_STATIC_48                   1165
#define IDC_STATIC_JOINDELAY1           1165
#define IDC_ACC_O2                      1166
#define IDC_STATIC_JOINDELAY2           1166
#define IDC_STATIC_49                   1167
#define IDC_STATIC_JOINNUM              1167
#define IDC_ACC_CO                      1168
#define IDC_STATIC_LORASTATUS           1168
#define IDC_STATIC_50                   1169
#define IDC_ACC_H2S                     1170
#define IDC_STATIC_51                   1171
#define IDC_ACC_MIPEX                   1172
#define IDC_SET_O2COEFF2                1173
#define IDC_SET_O2COEFFDEF2             1174
#define IDC_RADIO1                      1175
#define IDC_RADIO2                      1176
#define IDC_SET_SENSORSTATUS            1177
#define IDC_GET_SENSORSTATUS            1178
#define IDC_STATIC_52                   1179
#define IDC_EDIT52                      1180
#define IDC_STATIC_53                   1181
#define IDC_EDIT53                      1182
#define IDC_STATIC_54                   1183
#define IDC_EDIT54                      1184
#define IDC_STATIC_55                   1185
#define IDC_EDIT55                      1186
#define IDC_STATIC_56                   1187
#define IDC_EDIT56                      1188
#define IDC_STATIC_57                   1189
#define IDC_EDIT57                      1190
#define IDC_STATIC_58                   1191
#define IDC_EDIT58                      1192
#define IDC_SET_CH4COEFF                1193
#define IDC_SET_CH4COEFFDEF             1194
#define IDC_GETALL                      1195
#define IDC_ZERO_CH4                    1196
#define IDC_STATIC_59                   1196
#define IDC_FROM_CH4                    1197
#define IDC_EDIT59                      1197
#define IDC_TO_CH4                      1198
#define IDC_STATIC_60                   1198
#define IDC_MAX_CH4                     1199
#define IDC_EDIT60                      1199
#define IDC_ZERO_CO                     1200
#define IDC_STATIC_61                   1200
#define IDC_FROM_CO                     1201
#define IDC_EDIT61                      1201
#define IDC_TO_CO                       1202
#define IDC_STATIC_62                   1202
#define IDC_MAX_CO                      1203
#define IDC_EDIT62                      1203
#define IDC_ZERO_H2S                    1204
#define IDC_STATIC_63                   1204
#define IDC_FROM_H2S                    1205
#define IDC_EDIT63                      1205
#define IDC_TO_H2S                      1206
#define IDC_STATIC_64                   1206
#define IDC_MAX_H2S                     1207
#define IDC_EDIT64                      1207
#define IDC_ZERO_O2                     1208
#define IDC_SET_CH4MULT                 1208
#define IDC_FROM_O2                     1209
#define IDC_STATIC_65                   1209
#define IDC_TO_O2                       1210
#define IDC_EDIT65                      1210
#define IDC_MAX_O2                      1211
#define IDC_STATIC_66                   1211
#define IDC_SET_GASRANGE                1212
#define IDC_EDIT66                      1212
#define IDC_GET_GASRANGE                1213
#define IDC_STATIC_67                   1213
#define IDC_SET_VRANGE                  1214
#define IDC_SET_VIBROPOWER              1214
#define IDC_GET_VRANGE                  1215
#define IDC_GET_VIBROPOWER              1215
#define IDC_GRID_VRANGE                 1216
#define IDC_SET_ALLGASRANGE             1216
#define IDC_GRID_ALARMS                 1217
#define IDC_SET_COEFF                   1217
#define IDC_VIBROPOWER                  1218
#define IDC_SET_COEFFDEF                1218
#define IDC_EDIT67                      1218
#define IDC_SET_ALARMS                  1219
#define IDC_STATIC_68                   1219
#define IDC_SET_ALARMSDEF               1220
#define IDC_EDIT68                      1220
#define IDC_GET_ALARMS                  1221
#define IDC_STATIC_69                   1221
#define IDC_O2UNITS                     1222
#define IDC_EDIT69                      1222
#define IDC_COUNITS                     1223
#define IDC_STATIC_70                   1223
#define IDC_H2SUNITS                    1224
#define IDC_EDIT70                      1224
#define IDC_CH4UNITS                    1225
#define IDC_STATIC_71                   1225
#define IDC_SET_UNITS                   1226
#define IDC_EDIT71                      1226
#define IDC_GET_UNITS                   1227
#define IDC_FACTORYRESET                1228
#define IDC_STARTZEROCALIBRATION        1229
#define IDC_CANCELZEROCALIBRATION       1230
#define IDC_STARTCALIBRATION            1231
#define IDC_CANCELCALIBRATION           1232
#define IDC_CHECK_O2FACTORY             1233
#define IDC_CO_FACTORY                  1234
#define IDC_CHECK_H2FACTORY             1235
#define IDC_CHECK_CH4_FACTORY           1236
#define IDC_EDIT_O2                     1237
#define IDC_EDIT_H2S                    1238
#define IDC_GRID_SETTINGS               1239
#define IDC_STARTZEROCALIBRATIONALL     1239
#define IDC_GET_SETTINGS                1240
#define IDC_STARTCALIBRATIONALL         1240
#define IDC_GRID_TYPES                  1240
#define IDC_SET_SETTINGS                1241
#define IDC_FACTORY_ALL                 1241
#define IDC_TESTALARM1                  1242
#define IDC_SET_UNITSALL                1242
#define IDC_TESTALARM2                  1243
#define IDC_FREQ1                       1243
#define IDC_CANCELFACTORYRESET          1243
#define IDC_ALARM_OFF                   1243
#define IDC_SF1                         1244
#define IDC_O2_PREC                     1244
#define IDC_GRID_EXT                    1244
#define IDC_LIFETIME1                   1245
#define IDC_CO_PREC                     1245
#define IDC_FREQ2                       1246
#define IDC_H2S_PREC                    1246
#define IDC_SF2                         1247
#define IDC_CH4_PREC                    1247
#define IDC_LIFETIME2                   1248
#define IDC_SET_PRECISIONS              1248
#define IDC_FREQ3                       1249
#define IDC_GET_PRECISIONS              1249
#define IDC_SF3                         1250
#define IDC_SET_PRECISIONSALL           1250
#define IDC_LIFETIME3                   1251
#define IDC_O2_AUTOZERO                 1251
#define IDC_ADDR                        1252
#define IDC_CO_AUTOZERO                 1252
#define IDC_SET_RF                      1253
#define IDC_H2S_AUTOZERO                1253
#define IDC_DATEPERIOD                  1254
#define IDC_CH4_AUTOZERO                1254
#define IDC_GET_RF                      1255
#define IDC_SET_AUTOZERO                1255
#define IDC_SET_RFDEF                   1256
#define IDC_GET_AUTOZERO                1256
#define IDC_LIFETIME_ALL                1257
#define IDC_SET_AUTOZEROALL             1257
#define IDC_NKEY                        1258
#define IDC_SCALE_AUTOZERO              1258
#define IDC_AKEY                        1259
#define IDC_GRID_SCALE                  1259
#define IDC_STATIC_STEP                 1260
#define IDC_SET_KEYS                    1260
#define IDC_SET_SCALE                   1260
#define IDC_GET_KEYS                    1261
#define IDC_GET_SCALE                   1261
#define IDC_POWER1                      1262
#define IDC_POWER2                      1263
#define IDC_POWER3                      1264
#define IDC_SENDPACKET                  1265
#define IDC_RESET                       1266
#define IDC_RX1DELAY                    1266
#define IDC_GET                         1267
#define IDC_RX2DELAY                    1267
#define IDC_GRID_STAT                   1268
#define IDC_GET_ALL                     1268
#define IDC_DEVEUI                      1268
#define IDC_BUTTON1                     1269
#define IDC_JOINEUI                     1269
#define IDC_COMMAND                     1270
#define IDC_ROOTKEY                     1270
#define IDC_START                       1271
#define IDC_SENDALL                     1271
#define IDC_JOINDELAY1                  1271
#define IDC_FROMPREV                    1271
#define IDC_STOP                        1272
#define IDC_JOINDELAY2                  1272
#define IDC_BACKUP                      1272
#define IDC_T                           1272
#define IDC_POLLTIME                    1273
#define IDC_JOINNUM                     1273
#define IDC_RESTORE                     1273
#define IDC_TTIME                       1273
#define IDC_LIST_CURVES                 1274
#define IDC_SET_OTAA                    1274
#define IDC_COEFF                       1274
#define IDC_CONC                        1274
#define IDC_STATIC_LOG                  1275
#define IDC_SAVE                        1275
#define IDC_GET_OTAA                    1275
#define IDC_GASTIME                     1275
#define IDC_LASTCOMMAND                 1275
#define IDC_WAITTIME                    1276
#define IDC_LORASTATUS                  1276
#define IDC_START2                      1276
#define IDC_SAVE2                       1276
#define IDC_FREQ_RX                     1277
#define IDC_SAVECSVALL                  1277
#define IDC_OPENFOLDER                  1277
#define IDC_PROGRESS1                   1278
#define IDC_SF_RX                       1278
#define IDC_GRID_LOG                    1279
#define IDC_COMBO_STANDARD              1279
#define IDC_RADIO_LOG                   1280
#define IDC_COMBO_MODULE                1280
#define IDC_COMBO_POWER                 1280
#define IDC_RADIO_GRAPH                 1281
#define IDC_COMBO_PROTOCOL              1281
#define IDC_COMBO_SECURITY              1281
#define IDC_FORWARD                     1282
#define IDC_RADIO_DATA                  1282
#define IDC_SET_INTERFACE               1282
#define IDC_COMBO_IPPROTOCOL            1282
#define IDC_BACKWARD                    1283
#define IDC_GET_INTERFACE               1283
#define IDC_SET                         1283
#define IDC_SAVECSV                     1284
#define IDC_REGION                      1284
#define IDC_EDIT_MEAN                   1285
#define IDC_SAVEALL                     1285
#define IDC_SENDFIRMWARE                1286
#define IDC_LAST                        1286
#define IDC_RUNFIRMWARE                 1287
#define IDC_CONC_O2                     1288
#define IDC_SENDFIRMWAREALL             1288
#define IDC_AUTOSAVE                    1289
#define IDC_CONC_CO                     1290
#define IDC_RICHEDIT21                  1290
#define IDC_CONC_H2S                    1291
#define IDC_BASE                        1291
#define IDC_CONC_C3H8                   1292
#define IDC_STATIC_RXSETTINGS           1292
#define IDC_BASE2                       1292
#define IDC_SELINFO                     1292
#define IDC_CONC_CH4                    1293
#define IDC_STATIC_OTAA                 1293
#define IDC_CHECK_ABP                   1294
#define IDC_CHECK_OTAA                  1295
#define IDC_REJOIN                      1296
#define IDC_STATIC_ACTIVATION           1297
#define IDC_STATIC_WORKMODE             1297
#define IDC_REPEAT                      1298
#define IDC_REPEATTIME                  1299
#define IDC_CLEAR                       1300
#define IDC_REPEATALL                   1301
#define IDC_RXWINDOW_GROUP              1302
#define IDC_STATIC_RXFREQ               1303
#define IDC_STATIC_SFRX                 1304
#define IDC_SETALL                      1307
#define IDC_CHECK_DEVICEMODE            1308
#define IDC_CHECK_O2                    1309
#define IDC_CHECK_CO                    1310
#define IDC_CHECK_H2S                   1311
#define IDC_CHECK_CH4                   1312
#define IDC_CHECK_ACCEL                 1313
#define IDC_CHECK_SENSORSTATUS          1314
#define IDC_CHECK_MEASUREDIAP           1315
#define IDC_CHECK_VOLTDIAP              1316
#define IDC_CHECK_UNITS                 1317
#define IDC_CHECK_LIMITS                1318
#define IDC_SET_ALL                     1319
#define IDC_COMBO1                      1320
#define IDC_COEFFVOLTOLEL               1321
#define IDC_COEFFCOPPMTOMG              1322
#define IDC_COEFFH2SPPMTOMG             1323
#define IDC_COEFFCHEMPPMTOMG            1324
#define IDC_OCHEM                       1325
#define IDC_BUTTON2                     1326
#define IDC_INFO                        1327
#define IDC_STATIC_O2UNITS              1328
#define IDC_STATIC_COUNITS              1329
#define IDC_STATIC_H2SUNITS             1330
#define IDC_STATIC_CH4UNITS             1331
#define IDC_STATIC_CALO2UNITS           1332
#define IDC_STATIC_CALCOUNITS           1333
#define IDC_STATIC_CALH2SUNITS          1334
#define IDC_STATIC_CALCH4UNITS          1335
#define IDC_HOTKEY1                     1336
#define IDC_WOCONFIRM                   1337
#define IDC_WITHCONFIRM                 1338
#define IDC_LORASIGNALSTATUS            1339
#define IDC_RADIO_MIPEX                 1340
#define IDC_RADIO_UART                  1341
#define IDC_RADIO_SPI                   1342
#define IDC_RADIO_D                     1343
#define IDC_RADIO_DA                    1344
#define IDC_STATIC_MIN                  1344
#define IDC_STATIC_MAX                  1345
#define IDC_STATIC_02                   1346
#define IDC_STATIC_03                   1347
#define IDC_STATIC_04                   1348
#define IDC_STATIC_05                   1349
#define IDC_STATIC_06                   1350
#define IDC_STATIC_07                   1351
#define IDC_STATIC_08                   1352
#define IDC_STATIC_09                   1353
#define IDC_STATIC_CH4                  1354
#define IDC_STATIC_CO                   1355
#define IDC_STATIC_H2S                  1356
#define IDC_STATIC_O2                   1357
#define IDC_FROMFILE                    1358
#define IDC_STATIC_RADIOCHAN            1359
#define IDC_RADIO_WAN                   1360
#define IDC_RADIO_P2P                   1361
#define IDC_STATIC_ABP                  1362
#define IDC_STATIC_NWSKEY               1363
#define IDC_STATIC_APPSKEY              1364
#define IDC_STATIC_CH2                  1365
#define IDC_STATIC_CH3                  1366
#define IDC_STATIC_FREQ2                1367
#define IDC_STATIC_FREQ3                1368
#define IDC_STATIC_SF2                  1369
#define IDC_STATIC_SF3                  1370
#define IDC_STATIC_POWER2               1371
#define IDC_STATIC_POWER3               1372
#define IDC_STATIC_LT2                  1373
#define IDC_STATIC_LT3                  1374
#define IDC_STATIC_ACTIV                1375
#define IDC_CHECK_MIPEXSTATUS           1376
#define IDC_GROUP_MIPEX                 1380
#define IDC_STATIC_SCALE                1381
#define IDC_COMBO_MIPEX                 1382
#define IDC_COMBO_O2                    1383
#define IDC_GROUP_O2                    1384
#define IDC_GROUP_CO                    1385
#define IDC_COMBO_O3                    1386
#define IDC_COMBO_CO                    1386
#define IDC_PRESSURE                    1387
#define IDC_STATIC_WEEKTOSCALE          1388
#define IDC_COMBO_O2_POS                1388
#define IDC_COMBO_CO_POS                1389
#define IDC_COMBO_H2S_POS               1390
#define IDC_COMBO_MIPEX_POS             1391
#define IDC_COMBO_H2S                   1392
#define IDC_GROUP_H2S                   1393
#define IDC_FILEPATH                    1394
#define IDC_QUALITY                     1395
#define IDC_GROUP_CH4_MULT              1396
#define IDC_SHORTLOG                    1397
#define IDC_STATIC_DIAP                 1398
#define IDC_MIPEXLOG                    1398
#define IDC_STATIC_FROM                 1399
#define IDC_ACCUM                       1399
#define IDC_STATIC_TO                   1400
#define IDC_STATIC_STANDARD             1401
#define IDC_STATIC_MODULE               1402
#define IDC_STATIC_STANDARD2            1402
#define IDC_STATIC_PROTOCOL             1403
#define IDC_STATIC_STANDARD3            1403
#define IDC_SSID                        1404
#define IDC_STATIC_STANDARD4            1405
#define IDC_STATIC_STANDARD5            1406
#define IDC_SECURITYKEY                 1407
#define IDC_STATIC_STANDARD6            1408
#define IDC_COMBO_CHANNEL               1409
#define IDC_STATIC_STANDARD7            1410
#define IDC_LOCALIP                     1411
#define IDC_STATIC_STANDARD8            1412
#define IDC_LOCALPORT                   1413
#define IDC_STATIC_STANDARD9            1414
#define IDC_REMOTEIP                    1415
#define IDC_STATIC_STANDARD10           1416
#define IDC_REMOTEPORT                  1417
#define IDC_DATAPERIOD                  1418
#define IDC_STATIC_STANDARD11           1419
#define IDC_MAC                         1420
#define IDC_STATIC_STANDARD12           1421
#define IDC_TCPSERVERPORT               1422
#define IDC_GRID_RSSI                   1423
#define IDC_GROUP_RSSI                  1424
#define IDC_STATIC_VOLTOLEL             1425
#define IDC_STATIC_IDSENSOR             1426
#define IDC_STATIC_IDCPU                1427
#define IDC_STATIC_COPPMTOMG            1428
#define IDC_STATIC_H2SPPMTOMG           1429
#define IDC_STATIC_O2PPMTOMG            1430
#define IDC_ADD                         1431
#define IDC_MOD                         1432
#define IDC_DEL                         1433
#define IDC_SEND                        1434
#define IDC_GRID_ARRAY                  1435
#define IDC_TIMEELAPSED                 1436
#define IDC_PROFILE                     1437
#define IDC_MOD_PROFILE                 1439
#define IDC_DEL_PROFILE                 1440
#define IDC_MENU                        1441
#define IDC_GRID_RESULT                 1442
#define IDC_CAMERATYPE                  1444
#define IDC_STATIC_T                    1445
#define IDC_CAMERAPORT                  1446
#define IDC_STATIC_CONC                 1446
#define IDC_STATIC_TSET                 1447
#define IDC_GAS                         1447
#define IDC_CAMERAADDTIME               1447
#define IDC_STATIC_TSTATUS              1448
#define IDC_VALVE                       1448
#define IDC_CAMERAMAXTIME               1448
#define IDC_GASPORT                     1449
#define IDC_STATIC_VALVE                1449
#define IDC_BKGAS                       1450
#define IDC_10CHAN                      1450
#define IDC_BKVALVE                     1451
#define IDC_CAMERAINTERVAL              1451
#define IDC_BKCONC                      1452
#define IDC_ROOMTEMP                    1452
#define IDC_SLAVEID                     1453
#define IDC_OFFAFTER                    1453
#define IDC_CAMERASETTINGS              1454
#define IDC_STOPALLAFTER                1455
#define ID_AXISPROPERTIES               32771
#define ID_CURVESHOW                    32772
#define IDC_CURVEPROPERTIES             32773
#define ID_AXIS                         32774
#define ID_MAXIMIZE                     32775
#define ID_SETMARKER                    32776
#define ID_SETFILTER                    32778
#define ID_DOCK                         32779
#define ID_SETOWNLIMITS                 32780
#define ID_COPYCURVE                    32781
#define ID_HIDE                         32782
#define ID_PASTECURVE                   32783
#define ID_DIMYEARS                     32784
#define ID_DIMPPB                       32785
#define ID_DIMPPM                       32786
#define ID_SHOWADDLINES                 32787
#define ID_LOG                          32788
#define ID_DELETECURVE                  32795
#define ID_DELETEGRAPH                  32796
#define ID_SHOWLEGEND                   32797
#define ID_HIDELEGEND                   32798
#define ID_FONTLEGEND                   32799
#define ID_SETFONTLEGENDASDEFAULT       32800
#define ID_AUTORESCALE                  32807
#define ID_SHOWALLCURVES                32815
#define ID_SETYFIXEDLEN                 32818
#define ID_LINKWITH                     32822
#define ID_ADDTRANDLINE                 32823
#define ID_SHOWLINES                    32824
#define ID_SHOWPOINTS                   32826
#define ID_ZOOM                         32827
#define ID_CANCEL                       32828
#define ID_POINTMODE                    32831
#define ID_AXISNAME                     32832
#define ID_AXISTITLE                    32833
#define ID_POINTTYPE                    32834
#define ID_SHOWDIM                      32835
#define ID_REVERSEX                     32840
#define ID_HIDEMARKERS                  32841
#define ID_MOVECURVE                    32843
#define ID_UNDOACTION                   32844
#define ID_DELETESELECTED               32858
#define ID_CUTSELECTED                  32859
#define ID_DELETEWITHSHIFT              32862
#define ID_CURVENAME                    32864
#define ID_DIMAUTO                      32867
#define ID_DIMMINUTES                   32868
#define ID_DIMHOURS                     32869
#define ID_DIMDAYS                      32870
#define ID_DIMWEEKS                     32871
#define ID_DIMMONTHS                    32872
#define ID_DIMSECONDS                   32873
#define ID_ZOOMALL                      32878
#define ID_CURVEDATA                    40002
#define ID_HORIZONTALMARKER             40003
#define ID_FIXEDYLIMITS                 40004
#define ID_SETAXIS                      40006

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        295
#define _APS_NEXT_COMMAND_VALUE         32771
#define _APS_NEXT_CONTROL_VALUE         1455
#define _APS_NEXT_SYMED_VALUE           105
#endif
#endif
